// This file has been generated by Specta. Do not edit this file manually.
export type CommitHash = [number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number, number];

export type Path = string[][];

export type Query = { type: "SelectWhere"; table_name: Path; select: SelectClause; where: WhereClause };

export type QueryResponse = { type: "All"; tuples: Value<WireRowId>[][] } | { type: "One"; values: Value<WireRowId>[] } | { type: "Present" } | { type: "Absent" };

export type SelectClause = { type: "All"; columns: number[] } | { type: "One"; columns: number[] } | { type: "Existence" };

export type Value<I> = I | number | string;

export type WhereClause = { type: "PrimaryKey"; values: Value<WireRowId>[] } | { type: "ExceptRowId"; values: Value<WireRowId>[] } | { type: "Generic"; values_at: ([number, Value<WireRowId>])[] };

/**
 *  The unique id that identifies each row in a table.
 * 
 *  It is managed by the database and read-only for the user.
 */
export type WireRowId = {
	commit: CommitHash,
	counter: number,
};
