docs:
  stage: build
  tags: [nix]

  script:
    - nix develop -c ./shake docs
    - ./ci-deploy

format-check:
  stage: build
  tags: [nix]
    
  script:
    - nix develop -c ./shake check

tests:
  stage: build
  tags: [nix]
  script:
    - nix develop -c ./shake test
