docs:
  stage: build
  tags: [nix]

  script:
    - ./shake docs
    - ./ci-deploy

check:
  stage: build
  tags: [nix]
    
  script:
    - ./shake check
    - ./shake test

vscode:
  stage: build
  tags: [nix]

  script:
    - ./geolog-lsp/scripts/package.sh
  artifacts:
    expire_in: 3 days
    paths:
      - geolog-lsp/client/geolog-lsp-client*.vsix
