docs:
  stage: build
  tags: [nix]

  script:
    - nix develop -c ./shake docs
    - ./ci-deploy

format-check:
  stage: build
  tags: [nix]
    
  script:
    - nix develop -c ./shake check

tests:
  stage: build
  tags: [nix]
  script:
    - nix develop -c ./shake build

tests:
  stage: build
  tags: [nix]
  script:
    - nix develop -c ./shake test

vscode:
  stage: build
  tags: [nix]

  script:
    - nix develop -c ./shake vsce
  artifacts:
    expire_in: 3 days
    paths:
      - geolog-lsp/client/geolog-lsp-client*.vsix
