// This file has been generated by Specta. Do not edit this file manually.
export type CommitHash = string;

export type Path = string[][];

/**  A temporary row ID that is valid only within a transaction. */
export type TempRowId = number;

/**  A reference to an existing row or a pending row in the current transaction. */
export type TxnWireRowId = { type: "Existing"; value: WireRowId } | { type: "Pending"; value: TempRowId };

export type Value<I> = I | number | string;

export type WhereClause = { type: "PrimaryKey"; values: Value<WireRowId>[] } | { type: "ExceptRowId"; values: Value<WireRowId>[] } | { type: "Generic"; values_at: ([number, Value<WireRowId>])[] };

/**
 *  The unique id that identifies each row in a table.
 * 
 *  It is managed by the database and read-only for the user.
 */
export type WireRowId = {
	commit: CommitHash,
	counter: number,
};
