allowBuilds:
  cbor-extract: false
  esbuild: true
  "@automerge/automerge-repo@https://codeload.github.com/onsetsoftware/automerge-repo/tar.gz/b39d94c5624a3497150e08ba18546f29222289d8#path:packages/automerge-repo": true
overrides:
  "@automerge/automerge": 3.3.2
  "@automerge/automerge-subduction": 0.16.1
