on:
  pull_request:
  merge_group:
  push:
    branches: [main]

name: Check

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Install Nix ❄️
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-26.05

      - name: Check licenses
        run: |
          nix-env -i just reuse -f '<nixpkgs>'
          just check-licenses

  rust-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt

      - name: Check formatting
        run: cargo fmt --check

  rust-clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy

      - name: Run Clippy
        run: cargo clippy --all-targets -- -D warnings

  rust-tests:
    runs-on: ubuntu-latest
    needs: [rust-fmt, rust-clippy]
    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Install just
        uses: extractions/setup-just@v3

      - name: Run tests
        run: just check-rust

  haskell-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Install Nix ❄️
        uses: cachix/install-nix-action@v31

      - name: Set up Cachix ♻️
        uses: cachix/cachix-action@v17
        with:
          name: coln
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Formatting (.hs)
        run: nix build .#format-hs

      - name: Formatting (.cabal)
        run: nix build .#format-cabal

      - name: Haskell Tests
        run: |
          RUN_CHECKS=$(nix build .#haskell-tests --no-link --print-out-paths)
          $RUN_CHECKS

  end-to-end-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Install Nix ❄️
        uses: cachix/install-nix-action@v31

      - name: Set up Cachix ♻️
        uses: cachix/cachix-action@v17
        with:
          name: coln
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Run end-to-end tests
        run: |
          nix develop --command just -f packages/coln-node-runtime/justfile build-and-test
