on:
  push:
    branches:
      - main

name: VSCode Extension

jobs:
  vscode-extension:
    runs-on: coln-runner

    steps:
      - name: Checkout ⬇️
        uses: actions/checkout@v6

      - name: Build extension
        run: |
          nix build .#vscode-extension --accept-flake-config
          mv result coln-vscode-extension.vsix

      - name: Upload artefact
        uses: actions/upload-artifact@v7
        with:
          name: vscode-extension
          path: coln-vscode-extension.vsix
          if-no-files-found: warn
          retention-days: 7
          archive: false
